### PR TITLE
Database

### PR DESCRIPTION
**Pull request by AchrafBoufer**

### CODE REVIEW

**Comment by mohtashim-ali** [comment]
Great demo! This follows Clean Arch and will make it easier to implement other features such as UserLogIn and SignUp.

**Comment by HamzaShariff** [comment]
Follows what Oliver advised us to do. Nice start.

**Comment by NofelYazdani** [comment]
It seems that the program now follows CA and SOLID principles a lot more than it did before. Good job 🍆

**Comment by krhobeck** [comment]
Good work so far, I'd love to see some added encryption and decryption:

https://howtodoinjava.com/java/java-security/aes-256-encryption-decryption/

Heres one link to how you can do it using AES-256 encryption.

Also, look at the case where no 'history.txt' file might exist, you should be able to generate one and put text into it. Same with the 'users.txt'.

**Comment by mohtashim-ali** [comment]
> Good work so far, I'd love to see some added encryption and decryption:
> 
> https://howtodoinjava.com/java/java-security/aes-256-encryption-decryption/
> 
> Heres one link to how you can do it using AES-256 encryption.
> 
> Also, look at the case where no 'history.txt' file might exist, you should be able to generate one and put text into it. Same with the 'users.txt'.

Interesting, if there is the time we can definitely implement this as security is important for users (in the real world).

**Review by mohtashim-ali — APPROVED** [review]
Through the live demo during out Tutorial meeting and looking through the code, the changes make sense and do not need to be changed.

**Pull request merged**
