### PR TITLE
Build matrix

### PR DESCRIPTION
**Pull request by mohtashim-ali**
made class for building matrix, but needs to be implemented to follow Matrix type

### CODE REVIEW

**Comment by mohtashim-ali** [comment]
Moved gateway classes to gateway package

**Comment by mohtashim-ali** [comment]
Finished class to return a Matrix, now I will temp add this to controller and will perfect it later

**Comment by NofelYazdani** [comment]
Long-awaited implementation. Good job mohtashim ali!! the Matrix builder looks good in my opinion.

**Comment by HamzaShariff** [comment]
Looks good! I can look over the class and try implementing.

**Comment by krhobeck** [comment]
Try to look for a faster way to ask the user the build the matrix, nice job.

**Pull request merged**
