### PR TITLE
Packaging by layer

### PR DESCRIPTION
**Pull request by mohtashim-ali**
Switched packing to packaging by layers

### CODE REVIEW

**Comment by theman333** [comment]
82 files in one push??? We're definitely getting a merge error.

**Comment by HamzaShariff** [comment]
This perfectly implements packaging and fixes our messy files that are all over the place. Nice work!

**Comment by mohtashim-ali** [comment]
> This perfectly implements packaging and fixes our messy files that are all over the place. Nice work!

Thank You! I hope we have a easier time changing our code since we will be able to see the layer we change

**Comment by krhobeck** [comment]
Please push less files next time, worried about merge errors occuring.

**Comment by mohtashim-ali** [comment]
> Please push less files next time, worried about merge errors occuring.

Noted, that is better for the future in-order to prevent any conflicts near the deadline.

**Comment by NofelYazdani** [comment]
I think this approach is a lot better, Look like you organized based on CA.

**Comment by NofelYazdani** [comment]
c94

**Comment by AchrafBoufer** [comment]
A lot more organized than it was before, really good work.

**Pull request merged**
