### PR TITLE
Created new classes

### PR DESCRIPTION
**Pull request by mohtashim-ali**
We created new classes and an interface to adhere to SOLID and Clean Arch.

### CODE REVIEW

**Comment by HamzaShariff** [comment]
Now we just gotta split up the files and organize the code to follow the design principles.

**Comment by mohtashim-ali** [comment]
> Now we just gotta split up the files and organize the code to follow the design principles.

Yup based on the feedback provided to us, these classes will make It easy to move code from WalkthroughCustomInput.

**Comment by AchrafBoufer** [comment]
Still gotta figure out some of the database stuff with interfaces but looks good so far.

**Comment by NofelYazdani** [comment]
based on the feedback, I think its more ideal to use an interface for history

**Pull request merged**
